import { Property } from '@/types';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Loft in Downtown',
    description: 'A beautiful and spacious loft in the heart of the city. Perfect for a weekend getaway.',
    price: 150,
    location: 'New York, NY',
    imageUrl: 'https://placehold.co/600x400/E2E8F0/4A5568?text=Loft',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    rating: 4.8,
    type: 'apartment',
  },
  {
    id: '2',
    title: 'Cozy Cottage by the Lake',
    description: 'Escape to this charming cottage with stunning lake views. Ideal for a romantic retreat.',
    price: 200,
    location: 'Lake Tahoe, CA',
    imageUrl: 'https://placehold.co/600x400/D4F1F4/4A5568?text=Cottage',
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    rating: 4.9,
    type: 'house',
  },
  {
    id: '3',
    title: 'Luxury Condo with Ocean View',
    description: 'Experience luxury living in this modern condo with breathtaking ocean views.',
    price: 350,
    location: 'Miami, FL',
    imageUrl: 'https://placehold.co/600x400/F4E1D2/4A5568?text=Condo',
    bedrooms: 3,
    bathrooms: 3,
    guests: 6,
    rating: 4.7,
    type: 'condo',
  },
    {
    id: '4',
    title: 'Rustic Cabin in the Woods',
    description: 'Unplug and unwind in this cozy cabin surrounded by nature.',
    price: 120,
    location: 'Asheville, NC',
    imageUrl: 'https://placehold.co/600x400/E9D8A6/4A5568?text=Cabin',
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    rating: 4.6,
    type: 'house',
  },
  {
    id: '5',
    title: 'Chic Apartment in Paris',
    description: 'Live like a local in this stylish apartment in the heart of Paris.',
    price: 250,
    location: 'Paris, France',
    imageUrl: 'https://placehold.co/600x400/BDB2FF/4A5568?text=Paris+Apt',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    rating: 4.9,
    type: 'apartment',
  },
  {
    id: '6',
    title: 'Beachfront Villa in Bali',
    description: 'Wake up to the sound of waves in this stunning beachfront villa.',
    price: 500,
    location: 'Bali, Indonesia',
    imageUrl: 'https://placehold.co/600x400/FFCDB2/4A5568?text=Villa',
    bedrooms: 4,
    bathrooms: 4,
    guests: 8,
    rating: 5.0,
    type: 'house',
  },
    {
    id: '7',
    title: 'Downtown Skyscraper Condo',
    description: 'A modern condo on the 50th floor with panoramic city views.',
    price: 400,
    location: 'Chicago, IL',
    imageUrl: 'https://placehold.co/600x400/A2D2FF/4A5568?text=Skyscraper',
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    rating: 4.8,
    type: 'condo',
  },
  {
    id: '8',
    title: 'Suburban Family Home',
    description: 'A spacious and comfortable home perfect for a family vacation.',
    price: 220,
    location: 'Austin, TX',
    imageUrl: 'https://placehold.co/600x400/CDB4DB/4A5568?text=Family+Home',
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    rating: 4.7,
    type: 'house',
  },
];
